version: '3.8'

services:
  stripe-checkout:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    env_file:
      - server/.env
    restart: unless-stopped
    volumes:
      # Mount for development (optional)
      - ./logs:/app/logs:rw