apiVersion: v1
kind: Service
metadata:
  name: stripe-checkout-service
  labels:
    app: stripe-checkout
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: stripe-checkout